name: openai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - openssl
  - ca-certificates
  - numpy
  - pandas
  - torch
  - pip:
      - accelerate==0.26.1
      - agentops==0.3.26
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - aiosqlite==0.20.0
      - airportsdata==20250224
      - alabaster==1.0.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anthropic==0.49.0
      - anyio==4.8.0
      - apify-client==1.9.2
      - apify-shared==1.3.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arxiv==2.1.3
      - arxiv2text==0.1.14
      - astor==0.8.1
      - astroid==3.3.8
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - asyncio==3.4.3
      - asyncssh==2.20.0
      - atomicwrites==1.4.1
      - attrs==25.1.0
      - autopep8==2.0.4
      - av==14.2.0
      - azure-core==1.32.0
      - azure-storage-blob==12.25.0
      - babel==2.17.0
      - backoff==2.2.1
      - backports-tarfile==1.2.0
      - beautifulsoup4==4.13.3
      - bibtexparser==1.4.3
      - binaryornot==0.4.4
      - black==25.1.0
      - bleach==6.2.0
      - botocore==1.37.11
      - cachetools==5.5.2
      - camel-ai==0.2.26
      - certifi==2025.1.31
      - cffi==1.17.1
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - cohere==5.14.0
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - cookiecutter==2.6.0
      - coverage==7.6.12
      - cryptography==44.0.1
      - cssselect==1.3.0
      - cssutils==2.11.1
      - curl-cffi==0.6.2
      - currency-symbols==2.0.3
      - cycler==0.12.1
      - dappier==0.3.3
      - dataclasses-json==0.6.7
      - datacommons==1.4.3
      - datacommons-pandas==0.0.3
      - datasets==3.3.2
      - debugpy==1.8.12
      - decorator==5.2.1
      - deepdiff==8.3.0
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - diff-match-patch==20241021
      - diffusers==0.25.1
      - dill==0.3.8
      - discord-py==2.5.2
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - docker==7.1.0
      - docstring-parser==0.15
      - docstring-to-markdown==0.15
      - docutils==0.21.2
      - docx==0.2.4
      - docx2txt==0.8
      - duckdb==1.2.1
      - duckduckgo-search==6.4.2
      - e2b==1.1.0
      - e2b-code-interpreter==1.0.5
      - emoji==2.14.1
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fake-useragent==2.0.3
      - faker==19.13.0
      - fastapi==0.115.11
      - fastavro==1.10.0
      - fastjsonschema==2.21.1
      - feedfinder2==0.0.4
      - feedparser==6.0.11
      - ffmpeg-python==0.2.0
      - ffmpy==0.5.0
      - filelock==3.17.0
      - filetype==1.2.0
      - firecrawl-py==1.6.8
      - fish-audio-sdk==2024.12.5
      - flake8==7.1.2
      - fonttools==4.56.0
      - fpdf==1.7.2
      - fqdn==1.5.1
      - free-proxy==1.1.3
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - future==1.0.0
      - genson==1.3.0
      - geojson==2.5.0
      - google-api-core==2.24.2
      - google-auth==2.38.0
      - google-cloud-core==2.4.3
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.69.1
      - googlemaps==4.10.0
      - gradio==3.50.2
      - gradio-client==0.6.1
      - greenlet==3.1.1
      - grpcio==1.67.1
      - grpcio-tools==1.67.1
      - h11==0.14.0
      - h2==4.2.0
      - hpack==4.1.0
      - html2text==2024.2.26
      - html5lib==1.1
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - httpx-ws==0.7.1
      - huggingface-hub==0.29.3
      - hyperframe==6.1.0
      - identify==2.6.9
      - idna==3.10
      - imageio==2.37.0
      - imagesize==1.4.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.5.2
      - inflection==0.5.1
      - iniconfig==2.0.0
      - interegular==0.3.3
      - intervaltree==3.1.0
      - ipykernel==6.29.5
      - ipython==8.32.0
      - ipywidgets==8.1.5
      - isodate==0.7.2
      - isoduration==20.11.0
      - isort==6.0.1
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jedi==0.19.2
      - jeepney==0.9.0
      - jellyfish==1.1.3
      - jieba3k==0.35.1
      - jinja2==3.1.5
      - jiter==0.8.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-path==0.3.4
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keyring==25.6.0
      - kiwisolver==1.4.8
      - langdetect==1.0.9
      - langsmith==0.3.42
      - lark==1.2.2
      - lazy-object-proxy==1.10.0
      - linkup-sdk==0.2.3
      - litellm==1.63.6
      - lxml==5.3.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mcp==1.9.0
      - mdurl==0.1.2
      - milvus-lite==2.4.11
      - mistralai==1.5.1
      - mistune==3.1.2
      - mock==5.2.0
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy==1.15.0
      - mypy-extensions==1.0.0
      - narwhals==1.30.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nebula3-python==3.8.2
      - neo4j==5.28.1
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - newspaper3k==0.2.8
      - nltk==3.9.1
      - nodeenv==1.9.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - notion-client==2.3.0
      - numpy==1.26.4
      - numpydoc==1.8.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - olefile==0.47
      - openai==1.79.0
      - openapi-schema-validator==0.6.3
      - openapi-spec-validator==0.7.1
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - opentelemetry-api==1.30.0
      - opentelemetry-exporter-otlp-proto-common==1.30.0
      - opentelemetry-exporter-otlp-proto-http==1.30.0
      - opentelemetry-proto==1.30.0
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - orderly-set==5.3.0
      - orjson==3.10.15
      - ormsgpack==1.8.0
      - outcome==1.3.0.post0
      - outlines==0.1.14
      - outlines-core==0.1.26
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.5.3
      - pandasai==2.4.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathable==0.4.4
      - pathspec==0.12.1
      - pdfminer-six==20240706
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - platformdirs==4.3.6
      - playwright==1.50.0
      - pluggy==1.5.0
      - portalocker==2.10.1
      - prance==23.6.21.0
      - praw==7.8.1
      - prawcore==2.4.0
      - pre-commit==3.8.0
      - primp==0.14.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - proto-plus==1.26.1
      - protobuf==5.29.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycodestyle==2.12.1
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.8.1
      - pydocstyle==6.3.0
      - pydub==0.25.1
      - pyee==12.1.1
      - pyflakes==3.2.0
      - pygithub==2.6.1
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pylint==3.3.4
      - pylint-venv==3.0.4
      - pyls-spyder==0.4.0
      - pymilvus==2.5.5
      - pymupdf==1.25.3
      - pynacl==1.5.0
      - pyowm==3.3.0
      - pyparsing==3.2.1
      - pypdf==5.3.1
      - pypdf2==3.0.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.17.0
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.16
      - pysocks==1.7.1
      - pytelegrambotapi==4.26.0
      - pytest==7.4.4
      - pytest-asyncio==0.23.8
      - pytest-cov==4.1.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - python-iso639==2025.2.18
      - python-json-logger==3.2.1
      - python-lsp-black==2.0.0
      - python-lsp-jsonrpc==1.1.2
      - python-lsp-server==1.12.2
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-oxmsg==0.0.2
      - python-slugify==8.0.4
      - pytoolconfig==1.3.1
      - pytz==2025.1
      - pyuca==1.2
      - pyxdg==0.28
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - qdarkstyle==3.2.3
      - qdrant-client==1.13.3
      - qstylizer==0.2.4
      - qtawesome==1.3.1
      - qtconsole==5.6.1
      - qtpy==2.4.3
      - rank-bm25==0.2.2
      - rapidfuzz==3.12.2
      - redis==5.2.1
      - referencing==0.36.2
      - regex==2024.11.6
      - reka-api==3.2.0
      - requests==2.32.3
      - requests-file==2.1.0
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rope==1.13.0
      - rouge==1.0.1
      - rpds-py==0.23.1
      - rsa==4.9
      - rtree==1.3.0
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.5.3
      - scenedetect==0.6.6
      - scholarly==1.7.11
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - secretstorage==3.3.3
      - selenium==4.29.0
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==3.4.1
      - sentencepiece==0.2.0
      - sgmllib3k==1.0.0
      - shellingham==1.5.4
      - six==1.17.0
      - slack-bolt==1.22.0
      - slack-sdk==3.34.0
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soupsieve==2.6
      - sphinx==8.1.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - spyder==6.0.4
      - spyder-kernels==3.0.3
      - sqlalchemy==2.0.39
      - sqlglot==25.34.1
      - sqlglotrs==0.3.0
      - sse-starlette==2.2.1
      - stack-data==0.6.3
      - starlette==0.46.1
      - stem==1.8.2
      - stripe==11.6.0
      - superqt==0.7.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tavily-python==0.5.1
      - tenacity==9.1.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - text-unidecode==1.3
      - textblob==0.17.1
      - textdistance==4.6.3
      - threadpoolctl==3.5.0
      - three-merge==0.1.1
      - tiktoken==0.7.0
      - tinycss2==1.4.0
      - tinysegmenter==0.3
      - tldextract==5.1.3
      - tokenizers==0.21.0
      - tomli==2.2.1
      - tomlkit==0.13.2
      - torch==2.4.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.49.0
      - tree-sitter==0.23.2
      - tree-sitter-python==0.23.6
      - trio==0.29.0
      - trio-websocket==0.12.2
      - triton==3.0.0
      - typer==0.15.2
      - types-colorama==0.4.15.20240311
      - types-mock==5.2.0.20250306
      - types-python-dateutil==2.9.0.20241206
      - types-pyyaml==6.0.12.20241230
      - types-requests==2.32.0.20250306
      - types-setuptools==69.5.0.20240522
      - types-tqdm==4.67.0.20250301
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.1
      - ujson==5.10.0
      - unstructured==0.16.20
      - unstructured-client==0.27.0
      - update-checker==0.18.0
      - uri-template==1.3.0
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - virtualenv==20.29.3
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - whatthepatch==1.0.7
      - widgetsnbextension==4.0.13
      - wikipedia==1.4.0
      - wolframalpha==5.1.3
      - wrapt==1.17.2
      - wsproto==1.2.0
      - wurlitzer==3.1.1
      - xlrd==2.0.1
      - xls2xlsx==0.2.0
      - xmltodict==0.14.2
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.18.3
      - yt-dlp==2024.12.23
      - zipp==3.21.0
      - zstandard==0.23.0

